host: localhost:8080
info:
  contact:
    name: API Support
  description: This is a library API
  license:
    name: MITLicense
  termsOfService: N/A
  title: Library API
  version: "1.0"
paths: {}
swagger: "2.0"
